lfspinnerBeta/Controllers/MeetController.cs
// Kontroler Obslugujacy Opis LifeSpinner'a
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lfspinnerBeta.Controllers
{
    //[RequireHttps]
    public class MeetController : Controller
    {
        //
        // GET: /Meet/

        public ActionResult Index()
        {
            return View();
        }

    }
}

lfspinnerBeta/Controllers/PoliticsController.cs
// Kontroler do Obslugi regulaminow, umow itp 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lfspinnerBeta.Controllers
{
    [RequireHttps]
    public class PoliticsController : Controller
    {
        //
        // GET: /Politics/

        public ActionResult Index() // -> wybor dokumentu do odczytu
        {
            return View();
        }


        //
        // GET: /Politics/Cookie

        public ActionResult Cookie()
        {
            return View();
        }


        //
        // GET: /Politics/Regulations

        public ActionResult Regulations()
        {
            return View();
        }

        //
        // GET: /Politics/PersonalData

        public ActionResult PersonalData()
        {
            return View();
        }

          //
        // GET: /Politics/PrivacyPolicy

        public ActionResult PrivacyPolicy()
        {
            return View();
        }
        
    }
}

lfspinnerBeta/Views/Shared/_Layout.cshtml
<!--Layout do panelu powitalnego oraz do logowania rejestracji jak zapomnienia hasła-->
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content=""/>
    <meta name="keywords" content="" />
    <meta name="author" content="SpinnerGroup"/>
    <link rel="icon" href="images/favicons/favicon-32.bmp"/>

    <title>LifeSpinner - Profesjonalny system treningowy</title>

    <link href='http://fonts.googleapis.com/css?family=Cabin:400,600|Open+Sans:300,600,400' rel='stylesheet'>
    @Styles.Render("~/Content/css")
    
</head>
<body>

    <header class="header" data-stellar-background-ratio="0.5" id="home">

        <!-- COLOR OVER IMAGE -->
        <div class="overlay-layer">



            <!-- CONTAINER -->
            <div class="container">


                <div class="row">
                    <div class="col-md-7 text-left">

                        <!-- HEADING AND BUTTONS -->
                        <div class="intro-section intro-only-logo">


                            <img class="only-logo" src=@Url.Content("~/images/logo_biale.png") alt="">
                            <!-- WELCOM MESSAGE -->
                            <h1 class="intro white-text">Bezpieczny i przyjazny system klubów fitness</h1>

                            <p class=" hidden-xs transparent-text">Prezentacja trenera? Przeprowadzenie profesjonalnego treningu personalnego bez stosu kartek i notatek? W pełni automatyczna prezentacja wyników dla każdego z klientów w jednym systemie? Teraz to możliwe! Poznaj zalety LifeSpinner.<br /> Wpróbuj system w akcji! Przez 30 dni korzystaj <b>za darmo!</b></p>

                            <!-- BUTTON -->
                            <div class="button">
                                @Html.ActionLink("Poznaj LifeSpinner", "", "Meet", null, new { @class = "btn btn-primary secondary-button" })
                            </div>
                            <!-- /END BUTTON -->

                        </div>

                    </div>

                    <div class=" intro-only-logo col-md-5 pull-right">

                        @RenderBody()


                    </div>

                </div>

            </div>
        </div>

        
    </header>

        <!-- FOOTER -->
        <footer class="footer grey-bg">
            ©2015 SpinnerGroup. All Rights Reserved

            <!-- OPTIONAL FOOTER LINKS -->
            <ul class="footer-links small-text">
                <li>
                    @Html.ActionLink("O LifeSpinner", "", "Home") 
                </li>
                <li>                  
                    @Html.ActionLink("Regulamin", "Regulations", "Politics", null, new { @class = "dark-text" })
                </li>
                <li>
                    @Html.ActionLink("Polityka prywatnosci", "PrivacyPolicy", "Politics", null, new { @class = "dark-text" })                  

                </li>
            </ul>

            <!-- SOCIAL ICONS -->
            <ul class="social-icons">
                <li>
                    <a href="http://facebook.pl" target="_blank"><span class="icon-social-facebook transparent-text-dark"></span></a>
                </li>
                <li>
                    <a href="https://twitter.com/?lang=pl" target="_blank"><span class="icon-social-twitter transparent-text-dark"></span></a>
                </li>
                <li>
                    <a href="https://plus.google.com/" target="_blank"><span class="icon-social-googleplus transparent-text-dark"></span></a>
                </li>
            </ul>

        </footer>
        

        
   


    


    

   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/myscripts")

    @RenderSection("scripts", required: false)
</body>
</html>